# Generated by Django 2.1 on 2018-08-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180815_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
